name: readme commit svg
on: 
  push:
  schedule:
    - cron '0 0 * * *'
jobs:
  publish-commit-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: commit-svg
        uses: lowlighter/metrics@latest
        with:
          filename: commit_calendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          token: ${{secrets.COMMIT_METRICS_SECRET}}
      