name: readme svg for special repo
on:
  push:
    branches:
      - master
      - dev
  schedule:
    #every day at 8 pm utc
    - cron:  '0 20 * * *'
jobs:
  create-commit-artifact:
    runs-on: ubuntu-latest
    env:
      COMMIT_CALENDAR_FILE: commit_calendar.svg
      LANGUAGES_FILE: programming_languages.svg
    timeout-minutes: 10

    steps:
      - name: create-svg-commits
        uses: lowlighter/metrics@latest
        with:
          filename: ${{ env.COMMIT_CALENDAR_FILE }}
          output_action: none
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/setup/action.md
          token: ${{secrets.COMMIT_METRICS_SECRET}}

      - name: create-svg-languages
        uses: lowlighter/metrics@latest
        with:
          filename: ${{ env.LANGUAGES_FILE }}
          output_action: none
          plugin_languages: yes
          plugin_languages_ignored: >-
            R, SAS
          token: ${{secrets.COMMIT_METRICS_SECRET}}

      - name: upload-commit-history-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: commit-history-artifacts
          overwrite: true
          path: |
            /metrics_renders/${{ env.COMMIT_CALENDAR_FILE }}
            /metrics_renders/${{ env.LANGUAGES_FILE }}


  publish-commit-artifact:
    permissions:
      contents: write
      id-token: write
    env:
      COMMIT_CALENDAR_FILE: commit_calendar.svg
      LANGUAGES_FILE: programming_languages.svg
      ORCHESTRATION_SCRIPT: './.github/scripts/orchestrate_artifacts.sh'
      PREVENT_DISABLE_SCRIPT: '.github/scripts/prevent_disable.sh'
    needs: create-commit-artifact
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout-current-branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: download-commit-history-artifacts
        uses: actions/download-artifact@v4
        with:
          name: commit-history-artifacts

      - name: script-execution-permissions
        run: chmod +x ${{env.ORCHESTRATION_SCRIPT}}


      - name: assume-github-actions-role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{vars.REGION_NAME}}
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{secrets.PIPELINE_ROLE_NAME}}

      - name: persist-image-artifacts
        shell: bash
        env:
          AWS_DEFAULT_OUTPUT: json
          AWS_DEFAULT_REGION: ${{vars.REGION_NAME}}
          AWS_S3_BUCKET_NAME: 'ryanrigato.com'
          AWS_S3_UPLOAD_PREFIX: 'github/'
        run: ${{env.ORCHESTRATION_SCRIPT}}


      ##################
      #Unnecessary orchestration because public workflows are auto
      #disabled after 60 days
      #
      #https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
      ##################
      - name: script-execution-permissions-disable
        run: chmod +x ${{env.PREVENT_DISABLE_SCRIPT}}

      - name: prevent-disabled-workflow
        shell: bash
        run: ${{env.PREVENT_DISABLE_SCRIPT}}
