name: readme svg for special repo
on: 
  push: 
  #   branches:
  #     - master
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 15 * * *'
jobs:
  publish-commit-artifact:
    runs-on: ubuntu-latest
    env: 
      COMMIT_CALENDAR_FILE: commit_calendar.svg
      ORCHESTRATION_SCRIPT: './.github/scripts/orchestrate_artifacts.sh'

    steps:
      - name: create-svg
        uses: lowlighter/metrics@latest
        with:
          filename: ${{ env.COMMIT_CALENDAR_FILE }}
          output_action: none
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/setup/action.md
          token: ${{secrets.COMMIT_METRICS_SECRET}}

      - name: checkout-current-branch
        uses: actions/checkout@v3

      - name: script-execution-permissions
        run: chmod +x ${{env.ORCHESTRATION_SCRIPT}}

      - name: persist-commit-artifact
        shell: bash
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.PERSISTANT_STORAGE_ID}}
          AWS_DEFAULT_OUTPUT: json
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_S3_BUCKET_NAME: 'ryanrigato.com'
          AWS_S3_UPLOAD_PREFIX: 'github/${{env.COMMIT_CALENDAR_FILE}}'
          AWS_SECRET_ACCESS_KEY: ${{secrets.PERSISTANT_STORAGE_KEY}}
        run: ${{env.ORCHESTRATION_SCRIPT}}

